Repository donghoony/webp_brick, pull requests merged in 2022-05, with the labels that each got.

#10 Feature: checkPaddleCollision 작성
  BrickBreaker.js
Labels: 기능 추가🚗, 공 🟡, 패들 ➖

#9 Feature: CheckCollision 작성
  BrickBreaker.js
Labels: 기능 추가🚗, 벽돌🧱, 공 🟡, 패들 ➖

#14 Refactor: 벽돌의 행 개수 수정
  BrickBreaker.js
Labels: 벽돌🧱, 리팩터링 🔧

#18 Feat: Paddle.calculate() 구현
  BrickBreaker.js
Labels: 기능 추가🚗, 패들 ➖

#19 Fix: 블럭 위치 수정
  BrickBreaker.js
Labels: 벽돌🧱, 리팩터링 🔧

#17 Feature: Item 구현
  BrickBreaker.js
Labels: 기능 추가🚗, 아이템 🎁

#20 Fix: 아이템 위치 수정
  BrickBreaker.js
Labels: 버그🐛, 아이템 🎁

#21 Refactor: Item.collision을 부모 클래스에 위치
  BrickBreaker.js
Labels: 리팩터링 🔧, 아이템 🎁

#26 Feature: 아이템 클래스에 시간 추가
  BrickBreaker.js
Labels: 기능 추가🚗, 아이템 🎁

#27 Feature: 패들 길이증가 아이템+ 시간 지난 후 감소 코드 추가
  BrickBreaker.js
Labels: 패들 ➖, 아이템 🎁

#24 Refactor: 공과 패들이 닿을 때 각도 수정
  BrickBreaker.js
Labels: 공 🟡, 패들 ➖, 리팩터링 🔧

#29 Feature: 게임 진행 로직 추가
  BrickBreaker.js
Labels: 기능 추가🚗

#16 Feature: HTML Layout 수정, Canvas 추가
  BrickBreaker.css
  BrickBreaker.html
  BrickBreaker.js
Labels: 기능 추가🚗, 리팩터링 🔧, HTML/CSS ✨

#37 Feature: 아이템 이미지 추가
  BrickBreaker.js
  src/egg1.png
  src/egg2.png
  src/egg3.png
  src/egg4.png
Labels: 기능 추가🚗, 아이템 🎁

#36 Feature: 공 이미지 추가
  BrickBreaker.js
  src/blue.png
  src/red.png
  src/yellow.png
Labels: 기능 추가🚗, 공 🟡

#35 Feature: 블럭 이미지 추가
  BrickBreaker.js
  src/brick1.png
  src/brick2.png
Labels: 버그🐛, 기능 추가🚗, 벽돌🧱

#32 html의 info 부분 canvas에서 div로 변경
  BrickBreaker.css
  BrickBreaker.html
  BrickBreaker.js
Labels: 리팩터링 🔧, HTML/CSS ✨

#33 Feature: 블럭 깰 때 점수 추가
  BrickBreaker.js
Labels: 기능 추가🚗

#34 Refactor: 게임 시작 방법 설정
  BrickBreaker.js
Labels: 리팩터링 🔧

#42 Feature: 음향 효과 추가
  BrickBreaker.js
  src/audio/ball_bounce.ogg
  src/audio/big_bird.ogg
  src/audio/itempadd.ogg
  src/audio/padd-.ogg
  src/audio/padd.ogg
  src/audio/게임진행.ogg
  src/audio/레벨1.ogg
  src/audio/레벨2.ogg
  src/audio/레벨성공.ogg
  src/audio/레벨실패.ogg
  src/audio/마지막레벨.ogg
  src/audio/시작화면.ogg
Labels: 기능 추가🚗, 음향 🔊

#46 Feature: 환경설정 추가
  BrickBreaker.css
  BrickBreaker.html
  BrickBreaker.js
Labels: 기능 추가🚗, 리팩터링 🔧, HTML/CSS ✨, 게임 진행 🎲

#48 Feature: 배경화면 이미지 삽입
  BrickBreaker.js
  src/backgroundimg/배경화면1.png
  src/backgroundimg/시작화면.png
Labels: 기능 추가🚗

#31 Feature: 무적 공 아이템 구현
  BrickBreaker.js
Labels: 기능 추가🚗, 공 🟡, 아이템 🎁

#50 Feature: 스코어 배수 아이템 추가
  BrickBreaker.js
Labels: 아이템 🎁

#40 Feature: 점수 추가
  BrickBreaker.html
  BrickBreaker.js
Labels: 기능 추가🚗

#51 Feature: 메뉴 이미지 / 패들 이미지 추가
  BrickBreaker.html
  BrickBreaker.js
  src/heart.png
  src/paddle.png
  src/wood.png
Labels: 패들 ➖, 게임 진행 🎲

#49 BGM 바뀌는 것 구헌, 시작화면 이미지 넣기 실패
  BrickBreaker.js
  src/backgroundimg/시작화면1.jpg
  src/backgroundimg/시작화면2.jpg
Labels: 음향 🔊

#53 디자인 변경, 벽돌 모양 구현
  BrickBreaker.css
  BrickBreaker.js
  src/backgroundimg/play화면.png
  src/backgroundimg/play화면2.png
  src/backgroundimg/게임오버.png
  src/backgroundimg/배경화면2.png
  src/backgroundimg/스코어보드.png
  src/backgroundimg/시작화면3.png
  src/backgroundimg/화면.png
  src/backgroundimg/화면1.png
Labels: HTML/CSS ✨

#45 3 Character에 대한 클래스 추가
  BrickBreaker.js
Labels: 기능 추가🚗
